/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model18(props) {
  const { nodes, materials } = useGLTF("/Model18.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Disco_g0_b0.geometry}
        material={materials.brush_Disco}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Disco_g0_b1.geometry}
        material={materials.brush_Disco}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Disco_g0_b2.geometry}
        material={materials.brush_Disco}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Electricity_g0_b0.geometry}
        material={materials.brush_Electricity}
      />
    </group>
  );
}

useGLTF.preload("/Model18.glb");
