/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model19(props) {
  const { nodes, materials } = useGLTF("/Model19.glb");
  return (
    <group {...props} dispose={null} scale={2} position={[0,1,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Light_g0_b0.geometry}
        material={materials.brush_Light}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Fire_g0_b0.geometry}
        material={materials.brush_Fire}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Dots_g0_b0.geometry}
        material={materials.brush_Dots}
      />
    </group>
  );
}

useGLTF.preload("/Model19.glb");