/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model6(props) {
  const { nodes, materials } = useGLTF("/Model6.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Streamers_g0_b0.geometry}
        material={materials.brush_Streamers}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_DiamondHull_g0_b0.geometry}
        material={materials.brush_DiamondHull}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_SoftHighlighter_g0_b0.geometry}
        material={materials.brush_SoftHighlighter}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Petal_g0_b0.geometry}
        material={materials.brush_Petal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_ThickPaint_g0_b0.geometry}
        material={materials.brush_ThickPaint}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_WigglyGraphite_g0_b0.geometry}
        material={materials.brush_WigglyGraphite}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_DuctTape_g0_b0.geometry}
        material={materials.brush_DuctTape}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_ChromaticWave_g0_b0.geometry}
        material={materials.brush_ChromaticWave}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Comet_g0_b0.geometry}
        material={materials.brush_Comet}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Comet_g0_b1.geometry}
        material={materials.brush_Comet}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.brush_Hypercolor_g0_b0.geometry}
        material={materials.brush_Hypercolor}
      />
    </group>
  );
}

useGLTF.preload("/Model6.glb");


 